# Generated by Django 5.0.6 on 2024-07-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('language_used', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in months')),
            ],
        ),
    ]
