# Generated by Django 5.0.7 on 2024-08-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp11', '0002_remove_book_authors_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
