# Generated by Django 5.0.7 on 2024-08-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp7', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
